### ISSUE TITLE
Initialize Repository: Integrate with Drizzle & GraphQL

### ISSUE THREAD

**Issue by G0maa** [activecourses/disworse#1]
- [x] Initialize NestJS project. (in docs)
- [x] Integrate with GraphQL. (in docs, use code first approach)
- [x] Integrate with Drizzle. (probably not in docs, you can create any dummy table)

**Comment by Holo-xy** [comment]
Didn't Khail say that he would do this?

**Comment by G0maa** [comment]
@Holo-xy Mention so we can get a notification. 

I think @alikehel is initializing frontend & monorepo only. He might do the first step `
Initialize NestJS project. (in docs)` in the process.

أو إلحقه قبل ما يعملها 😁

**Comment by alikehel** [comment]
>He might do the first step `Initialize NestJS project. (in docs)` in the process.

Yes I was gonna do this lol.

**Comment by G0maa** [comment]
> >He might do the first step `Initialize NestJS project. (in docs)` in the process.
> 
> Yes I was gonna do this lol.

Ok do it and @Holo-xy will continue with the remaining steps.

**Comment by G0maa** [comment]
Hello @Holo-xy, @alikehel is finished with setting up the repo, you can work on the remaining tasks.
